
POST http://localhost:4009/api/greet
Content-Type: application/json

{
    "language": "SeSotho",
    "greeting": "Dumela"
}

###
POST http://localhost:4009/api/greet
Content-Type: application/json

{
    "language": "Zulu",
    "greeting": "Sawubona"
}

###
POST https://first-api-greet.onrender.com/api/greet
Content-Type: application/json

{
    "language": "SeSotho",
    "greeting": "Dumela"
}
