
POST http://localhost:4009/api/greet
Content-Type: application/json

{
    "language": "SeSotho",
    "greeting": "Dumela"
}

###
POST http://localhost:4009/api/greet
Content-Type: application/json

{
    "language": "Zulu",
    "greeting": "Sawubona"
}

###
GET http://localhost:4009/api/greet?language=Zulu&greeting=Sawubona

###
POST https://first-api-greet.onrender.com/api/greet
Content-Type: application/json

{
    "language": "French",
    "greeting": "Bonjour"
}

### 
POST http://localhost:4009/api/language
Content-Type: application/json

{
    "new_language": "French",
    "new_greet": "Bonjour"
}
